### ISSUE TITLE
Slight incompatibility with Dorako UI module, text gets colored

### ISSUE THREAD

**Issue by shemetz** [shemetz/pf2e-see-simple-scale-statistics#11]
> having both Doraku UI and PF2e See Simple Scale Statistics it has become difficult to read the text:

![image](https://github.com/shemetz/pf2e-see-simple-scale-statistics/assets/6516621/4ff2e9e2-72d9-44d8-8d7e-9844913be25c)

![image](https://github.com/shemetz/pf2e-see-simple-scale-statistics/assets/6516621/b77a130e-8d04-4ed8-9c0b-afebcc63244d)

Reported by Dusky in the pf2e fvtt discord

**Comment by shemetz** [comment]
Dorako (module creator) supposedly had a solution for this already, which seems to not work this time?

![image](https://github.com/shemetz/pf2e-see-simple-scale-statistics/assets/6516621/29bc4675-9d5b-4c1b-ba3d-eb33ead54039)

**Comment by shemetz** [comment]
extra info that might help with debugging:
> I looked at the screenshots again and I've just noticed that specifically for the AC field, the blue isn't visible in dorako (but the blue IS visible on the damage buttons, oddly)
Did a quick check and the HP field behaves the same. Other colours are visible and look the same as the rest of the sheet, just seems to be the blue

**Comment by Dorako** [comment]
I would suggest not making any changes just yet. 
I'm moving a lot of code around, and introducing an entirely new application theme.
The above screenshot is a heatmap, the blue part is the old code and the orange part is new, added specifically for the Foundry 2 application theme, but not scoped to it because I didn't have a good structure to do so.
I spent yesterday making such a structure, so I'll be able to fix this soon enough.

**Comment by Dorako** [comment]
The blue on the AC is visible, it's just essentially undetectable on a red background.
The Foundry 2 theme uses a red background, which is why I had to change the glows to colored text. Seems like I've never had the blue glow though.

**Comment by Dorako** [comment]
![CleanShot 2023-10-22 at 19 38 22@2x](https://github.com/shemetz/pf2e-see-simple-scale-statistics/assets/1561190/91d62a6d-5fcb-436c-94e1-73d126717247)
There we go, back to looking normal with the default Dorako Light theme.
