### ISSUE TITLE
Please Add Option To Allow Dorako UI Interactive Token Coloring

### ISSUE THREAD

**Issue by raymergames** [shemetz/pf2e-see-simple-scale-statistics#12]
In the newest 1.4 version you haven't added a option to NOT automatically turn off Dorako UI's Colorize PF2e Interactive Tooltip's setting.

![Please Revert please](https://github.com/shemetz/pf2e-see-simple-scale-statistics/assets/84054111/d0bc5f4c-4e83-46b8-a5e9-41cedb54cdfb)

This might look cluttered, but to me, it looks WAY more legible despite the messiness. Can this feature please be a toggleable thing rather than a hard set one? It ain't pretty, but to me, this module isn't about looking pretty, it's about functionality. Which is why I thought the Toggleability in the main sheets was a smart middle-ground. 

Please give me back my pink brain! 🧠

**Comment by raymergames** [comment]
![please save me from this blandness](https://github.com/shemetz/pf2e-see-simple-scale-statistics/assets/84054111/302488e2-c8f4-4d33-9e63-847432c3094d)
The blandness hurts my soul. 😭

**Comment by shemetz** [comment]
Added again in v1.4.1, with a new settings option
