### ISSUE TITLE
[Bug] Colors not showing on AC or HP

### ISSUE THREAD

**Issue by Malkyn99** [shemetz/pf2e-see-simple-scale-statistics#16]
Title. Color coding on strikes now works again, but now appears gone for HP and AC, they're both white on Paizo-provided stat-blocks across the board.

**Comment by shemetz** [comment]
I can't reproduce this bug (in Foundry V12, pf2e system 6.0.1).  If it happens to you again, tell me exactly which actor it fails for and include a screenshot (maybe check console logs too).
