### ISSUE TITLE
Weakness/Resistances being color-codified in the wrong order

### ISSUE THREAD

**Issue by Calvin263** [shemetz/pf2e-see-simple-scale-statistics#17]
The image exemplifies the issue quite clearly:
The resistances and weaknesses are calculated correctly in the order they are input in the actor's sheet, but are applied as if they follow the same order. In reality, the weaknesses and resistances are alphabetized on the actor's sheet.

![image](https://github.com/user-attachments/assets/ee3dedbc-d3b7-4d03-8acf-2c4d71a63352)

In this example, the weaknesses were added in ascending order from 1 to 11.

**Comment by shemetz** [comment]
Nice catch!  Fixed in v1.4.5
