### ISSUE TITLE
button colors not shown when needed

### ISSUE THREAD

**Issue by ditzer252** [shemetz/pf2e-see-simple-scale-statistics#4]
When "Mark Stats" button is turned on the colors disappear.
I believe the desired behavior is to see the five colors on the button when the feature is turned on (personally it helps me remember that blue is better than green).  However, the button colors are only shown when the feature is off.
![image](https://user-images.githubusercontent.com/81697575/198007917-4ef750de-c1d8-4d02-a8ee-71cca2c7fa57.png)
![image](https://user-images.githubusercontent.com/81697575/198008478-89fb3e7f-a0e1-4a04-982e-c619398edf19.png)
If both the colors and the borders settings are turned on, then the button color behaves as expected.
Thank you.

**Comment by shemetz** [comment]
Fixed in v1.2.1
