### ISSUE TITLE
Module doesn't work and throws this exception

### ISSUE THREAD

**Issue by manituan** [shemetz/pf2e-see-simple-scale-statistics#6]
![image](https://user-images.githubusercontent.com/812457/219687778-db148010-ad08-4432-b1c2-f4a52e23b262.png)

**Comment by shemetz** [comment]
What sheet were you trying to open?

**Comment by shemetz** [comment]
...was it the Tarrasque?

**Comment by manituan** [comment]
Actually yes :)

**Comment by shemetz** [comment]
Fixed in the latest release :D 

The Tarrasque is a level 25 creature, and the creature building tables only go up to 24.  It's literally off the charts!

**Comment by manituan** [comment]
Thanks a lot
